package com.asistentewhatsapp.aiagents.domain;

public enum AgentIntent {
	GREETING, THANKS_OR_FAREWELL, COMMERCIAL_INQUIRY, SERVICE_INFORMATION, SERVICE_RECOMMENDATION, AVAILABILITY_QUERY, PROFESSIONAL_QUERY, LOCATION_QUERY, BUSINESS_HOURS_QUERY, PRICE_REQUEST, QUOTE_REQUEST, BOOKING_REQUEST, BOOKING_CHANGE, BOOKING_CANCEL, BOOKING_STATUS, PAYMENT_INQUIRY, PAYMENT_PROBLEM, SUPPORT_GENERAL, TECHNICAL_MESSAGE, KNOWLEDGE_QUERY, FOLLOW_UP, COMPLAINT, HUMAN_REQUEST, AMBIGUOUS, COMMERCIAL_AND_BOOKING, WAITLIST_QUERY
}
