package com.asistentewhatsapp.aiagents.domain;

public enum AgentIntent {
    GREETING,
    COMMERCIAL_INQUIRY,
    PRICE_REQUEST,
    QUOTE_REQUEST,
    BOOKING_REQUEST,
    BOOKING_CHANGE,
    BOOKING_CANCEL,
    BOOKING_STATUS,
    PAYMENT_INQUIRY,
    PAYMENT_PROBLEM,
    SUPPORT_GENERAL,
    TECHNICAL_MESSAGE,
    KNOWLEDGE_QUERY,
    FOLLOW_UP,
    COMPLAINT,
    HUMAN_REQUEST,
    AMBIGUOUS,
    COMMERCIAL_AND_BOOKING
}
