package com.asistentewhatsapp.channels.domain;

public enum WhatsAppChannelEventType {
	CHANNEL_CONFIGURED, NUMBER_REGISTERED, WEBHOOK_VERIFIED, CHANNEL_ACTIVATED, CHANNEL_DEACTIVATED, CONNECTION_VALIDATED, MESSAGE_RECEIVED, MESSAGE_SENT, AUTH_ERROR, CREDENTIAL_EXPIRED, DELIVERY_ERROR, SESSION_STATUS_CHANGED, QR_UPDATED, MESSAGE_ACK_UPDATED
}
