export {
  AdminSecurityPage,
  AdminUserCreatePage,
  AdminUserEditPage,
  AdminUsersPage,
  AutomationRuleCreatePage,
  AutomationRuleEditPage,
  AutomationRuleRunPage,
  AutomationRulesPage,
  CatalogCreatePage,
  CatalogEditPage,
  CatalogPage,
  ConversationOrderCreatePage,
  OrderCreatePage,
  OrderDetailPage,
  OrderPaymentPage,
  OrdersPage,
  ReportsPage,
} from './pages/VisualContractPages'
